image: node:20

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci
  - npx ng version || npm install -g @angular/cli # Install Angular CLI if not present

build:
  stage: build
  script:
    - npx ng build --configuration production
  artifacts:
    paths:
      - dist/
  only:
    - main

pages:
  stage: deploy
  script:
    - cp -r dist/* public/ # GitLab Pages needs a "public/" folder
  artifacts:
    paths:
      - public
  only:
    - main
