image: node:20

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci
  - npx ng version || npm install -g @angular/cli # Install Angular CLI if not present

build:
  stage: build
  script:
    - npx ng build --configuration production --base-href /recette/
  artifacts:
    paths:
      - dist/
  only:
    - main

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r dist/recette/browser/* public/
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - main
